spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/gameclub?serverTimezone=UTC&createDatabaseIfNotExist=true
  web:
    resources:
      static-locations: classpath:/static/,file:/uploads/
app:
  storage:
    location: /uploads/