spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gameclub?serverTimezone=UTC
    username: root
    password: KazimierzPrzerwaTetmajer
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:\Users\mikol\uploads
app:
  storage:
    location: \Users\mikol\uploads